---
name: Onboarding Pre-checks
on:
  push:
    branches:
    - main
    paths-ignore:
    - 'dotcms-onboarding-cicd/config/**'

permissions:
  id-token: write  # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  Fetch-Canada:
    runs-on: self-hosted
    env:
      AWS_REGION: 'ca-central-1'
    
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: Test dir access
        run: |
          ls -la
  
      - name: Fetching new customers/environments for ca-central-1 
        run: |
          # Store the output of the Python script in a local variable
          echo "CA_CENTRAL_1=$(python3 scripts/fetch_new.py)" >> $GITHUB_ENV
          python3 scripts/main.py
      
  # Fetch-US:
  #   runs-on: self-hosted
  #   env:
  #     AWS_REGION: 'us-east-1'
    
  #   steps:
  #   #   - name: Git clone the repository
  #   #     uses: actions/checkout@v3

  #     - name: Test dir access
  #       run: |
  #         cd /mnt/
  #         ls -la
      
  #     - name: Test dir access 
  #       run: |
  #         python3 ./fetch_new.py
