---
name: Onboarding Pre-checks
on:
  push:
    branches:
    - main
    paths-ignore:
    - 'poc2-automated-onboarding/config/**'

permissions:
  id-token: write  # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  Fetch-Canada:
    runs-on: [self-hosted,automated-onboarding-ec2]
    env:
      AWS_REGION: 'ca-central-1'
    
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ONBOARDING }}

      - name: Test dir access
        run: |
          ls -la
  
      - name: Fetching new customers/environments for ca-central-1 
        run: |
          TO_ONBOARD=$(python3 scripts/fetch_new.py)
          echo "TO_ONBOARD=$TO_ONBOARD" >> $GITHUB_ENV
          echo "Customers and envrionments to be onboarded: $TO_ONBOARD"
      
      - name: Onboarding Process
        run: |
          python3 scripts/main.py
    
      - name: Updating Onboarding Config file
        run: |
          python3 scripts/update_config.py
          git config --global user.name 'Automated onboarding'
          git config --global user.email 'automatedonboarding@dotcms.com'
          git add -A
          git diff --staged --quiet || (git commit -m "Update config onboarding ca-central-1" && git push)
  Fetch-US:
    runs-on: [self-hosted,us-east-1]
    env:
      AWS_REGION: 'us-east-1'
    
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ONBOARDING }}

      - name: Test dir access
        run: |
          ls -la
  
      - name: Fetching new customers/environments for us-east-1
        run: |
          TO_ONBOARD=$(python3 scripts/fetch_new.py)
          echo "TO_ONBOARD=$TO_ONBOARD" >> $GITHUB_ENV
          echo "Customers and envrionments to be onboarded: $TO_ONBOARD"
      
      - name: Onboarding Process
        run: |
          python3 scripts/main.py
    
      - name: Updating Onboarding Config file
        run: |
          python3 scripts/update_config.py
          git config --global user.name 'Automated onboarding'
          git config --global user.email 'automatedonboarding@dotcms.com'
          git add -A
          git diff --staged --quiet || (git commit -m "Update config onboarding us-east-1" && git push)