---
name: Onboarding Pre-checks
on:
  push:
    branches:
    - main
    paths-ignore:
    - 'dotcms-onboarding-cicd/config/**'

env:
  AWS_REGION: "ca-central-1"  # Change to reflect your Region

permissions:
  id-token: write  # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  Onboarding-pre-checks:
    runs-on: self-hosted

    steps:
      - id: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1

      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: Test dir access
        run: |
          cd /mnt/
          ls -la
      
      - name: Test dir access
        run: |
          python3 ./fetch_new.py