---
name: Onboarding Pre-checks
on:
  push:
    branches:
    - main
    paths-ignore:
    - 'dotcms-onboarding-cicd/config/**'

permissions:
  id-token: write  # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  Fetch-Canada:
    runs-on: self-hosted
    env:
      AWS_REGION: 'ca-central-1'
    
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: Test dir access
        run: |
          ls -la
  
      - name: Fetching new customers/environments for ca-central-1 
        run: |
          CA_CENTRAL_1=$(python3 scripts/fetch_new.py)
          echo "CA_CENTRAL_1=$CA_CENTRAL_1" >> $GITHUB_ENV
          echo "Customers and envrionments to be onboarded: $CA_CENTRAL_1"
      
      - name: Use env variable in a subsequent step
        run: |
          python3 scripts/main.py
          