---
name: Onboarding Pre-checks
on:
  push:
    branches:
    - main
    paths-ignore:
    - 'dotcms-onboarding-cicd/config/**'

env:
  AWS_REGION: "ca-central-1"  # Change to reflect your Region

permissions:
  id-token: write  # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  Onboarding-pre-checks:
    runs-on: ubuntu-latest

    steps:
      - id: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1

      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' 

      - name: Install dependencies
        run: |
          pip install pyyaml
          pip install yamllint